---
- hosts: all
  gather_facts: false

  tasks:
    - name: create user
      brightcomputing.bcm.user:
        name: "{{ user }}"
        password: "{{ pass }}"
        homeDirOperation: true
        

