---
- hosts: all
  gather_facts: false
  tasks:
    - name: clone default-image -> cloned-image
      brightcomputing.bcm.software_image:
        name: cloned-image
        cloneFrom: default-image
        path: /cm/images/cloned-image
