---
- hosts: all
  gather_facts: false
  tasks:
    - name: clone default category -> cloned category
      brightcomputing.bcm.category:
        name: cloned
        cloneFrom: default
        
    - name: set cloned category software image -> cloned-image
      brightcomputing.bcm.category:
        name: cloned
        softwareImageProxy: 
          parentSoftwareImage: cloned-image
          
    - name: clone default category -> k8s category
      brightcomputing.bcm.category:
        name: k8s
        cloneFrom: default
        
    - name: set k8s category software image -> cloned-image
      brightcomputing.bcm.category:
        name: k8s
        softwareImageProxy: 
          parentSoftwareImage: cloned-image