---
- hosts: all
  gather_facts: false

  tasks:     
    - name: configure auto-scaler
      brightcomputing.bcm.configuration_overlay:
        name: auto-scaler
        allHeadNodes: true
        roles_ScaleServerRole:
          - name: scaleserver
            runInterval: 60
            debug: true
            resourceProviders_ScaleDynamicNodesProvider:
              - name: "aws"
                templateNode: cnode003
                nodeRange: cnode003..cnode006
                networkInterface: eth0
                defaultResources: ['cpus=4','mem_free:slurm=16GB','gpu_free:t4:slurm=1']
            engines_ScaleHpcEngine:
              - name: slurm
                workloadsPerNode: 4
                wlmCluster: slurm
                trackers_ScaleHpcQueueTracker:
                  - name: gpu
                    queue: gpu
                    primaryOverlays: ['slurm-client']
                    allowedResourceProviders: ['aws']
                    workloadsPerNode: 4
 
                    