---
- hosts: all
  gather_facts: false

  tasks:  
     - name configure slurm cluster -> constrain devices
      brightcomputing.bcm.slurm_wlm_cluster:
        name: "slurm"
        cgroups:
          constrainDevices: true
    
    - name: clone defq -> gpu
      brightcomputing.bcm.slurm_job_queue:
        name: "gpu"
        cloneFrom: "defq"
        defaultQueue: false
        overSubscribe: "yes:4"
        wlmCluster: "slurm"
        
    - name: configure slurm-client overlay and slurmclient role
      brightcomputing.bcm.configuration_overlay:
        name: slurm-client
        categories: []
        categories: [ 'cloned' ]
        roles_SlurmClientRole:
          - name: slurmclient
            wlmCluster: "slurm"
            queues: ['gpu']
            boards: 1
            sockets: 1
            coresPerSocket: 2
            threadsPerCore: 2
            slots: 4
            realMemory: 15535
            genericResources:
              - name: "gpu"
                alias: "gpu0"
                file: "/dev/nvidia0"
                type: "t4"
                count: "1"  # must be a string
                consumable: true
                addToGresConfig: true
          