---
- hosts: all
  gather_facts: true
  
  tasks:
  
    - name: read all ec2 provider info
      brightcomputing.bcm.ec2_provider_info:
      register: result

    - name: set needed ec2_provider
      set_fact:
        aws_provider: "{{ result.ec2_providers | selectattr('name', 'equalto', 'amazon') | first }}"

    - name: set needed vpc
      set_fact:
        vpc:  "{{ aws_provider.VPCs[0] }}"
      
    # - name: print out the info that has been collected
      # debug:
        # msg:
          # - "secGroupD: {{ vpc.securityGroupDirector }}"
          # - "vpcID: {{ vpc.vpcID }}"
          # - "accesskeyId: {{ aws_provider.accessKeyId }}"
          # - "accessKeySecret: {{ aws_provider.accessKeySecret }}"
          # - "defaultRegion: {{ aws_provider.defaultRegion.name }}"
    
    - name: Create cm-jupyter-setup configuration file
      template:
        src: cm-jupyter-setup.conf.template
        dest: /root/cm-jupyter-setup.conf
        mode: 0644
      
    - name: Install Jupyter using the bash shell
      ansible.builtin.shell: cm-jupyter-setup -c /root/cm-jupyter-setup.conf
      args:
        executable: /bin/bash
    
    - name: Open port 8000 on the (cloud) head node
      ansible.builtin.shell: aws ec2 authorize-security-group-ingress --group-id {{ vpc.securityGroupDirector }} --protocol tcp --port 8000 --cidr 0.0.0.0/0
      args:
        executable: /bin/bash
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_provider.accessKeyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_provider.accessKeySecret }}"
        AWS_DEFAULT_REGION: "{{ aws_provider.defaultRegion.name }}"

  
