---
- hosts: all
  gather_facts: false

  tasks:
    - name: Install B4DS packages
      dnf:
        name: '{{ item }}'
        state: present
        update_cache: yes
        installroot: "/cm/images/cloned-image"
      with_items:
        - cm-tensorflow2-py37-cuda10.2-gcc
        - cm-openmpi-geib-cuda10.2-gcc8