---

install_dir: /root/.road-runner
update_head_node: no
ansible_version: 2.10.*

clone_software_image: yes

software_images:
  - cloned-image
 
cloned_software_image_name: 
  - cloned-image
  
categories:
  - name: cloned
    clone_from: default
    software_image: cloned-image
  - name: k8s
    clone_from: default
    software_image: cloned_image
  - name: jup
    clone_from: default
    software_image: cloned-image
  
deploy_jupyter: yes
jupyterhub_server: b91-c83-demo
jupyter_wlm_queue: jup
jupyter_wlm_categories: jup
jupyter_wlm_nodes: