---
- hosts: all
  gather_facts: false
  tasks:
    - name: Clone default-image -> cloned-image
      brightcomputing.bcm.software_image:
        name: cloned-image
        cloneFrom: default-image
        path: /cm/images/cloned-image
    
    - name: Clone default-image -> gpu-image
      brightcomputing.bcm.software_image:
        name: gpu-image
        cloneFrom: default-image
        path: /cm/images/gpu-image
