---
- hosts: all
  gather_facts: false
  tasks:
  - name: set node001 category -> cloned 
    brightcomputing.bcm.physical_node:
      hostname: node001
      category: cloned
      powerControl: custom
      
  - name: set node002 category -> cloned 
    brightcomputing.bcm.physical_node:
      hostname: node002
      category: cloned
      powerControl: custom
      
  - name: set node003 category -> cloned 
    brightcomputing.bcm.physical_node:
      hostname: node003
      category: cloned
      powerControl: "custom"
      
  - name: set node004 category -> gpu
    brightcomputing.bcm.physical_node:
      hostname: node004
      category: gpu
      powerControl: custom
      customPowerScript: /cm/local/apps/cmd/scripts/powerscripts/os-power-control.py
