---
- hosts: all
  gather_facts: false

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        update_cache: yes
        
    - name: Update default software image
      yum:
        name: "*"
        installroot: "/cm/images/default-image"
        state: latest
        update_cache: yes